name: 'mesh_warehouse'
version: '1.0'
config-version: 2

profile: 'mesh_warehouse'

model-paths: ['dispatch_logs', 'inventory', 'orders', 'returns', 'order_errors', 'ml_insights', 'dimensions']

on-run-start:
  - "{{ register_upstream_external_models() }}"
