mesh_warehouse:
  outputs:
    dev:
      type: duckdb
      path: ":memory:"
      extensions:
        - httpfs
        - iceberg
      secrets:
        - name: minio
          type: s3
          key_id: "{{ env_var('MINIO_ROOT_USER', 'minioadmin') }}"
          secret: "{{ env_var('MINIO_ROOT_PASSWORD', 'minioadmin') }}"
          endpoint: "{{ env_var('MINIO_ENDPOINT', 'http://minio:9000') }}"
          region: "us-east-1"
          url_style: "path"
          use_ssl: "false"
      attach:
        - path: "{{ env_var('ICEBERG_WAREHOUSE', 's3://warehouse') }}"
          type: iceberg
          alias: "{{ env_var('ICEBERG_CATALOG', 'minio') }}"
          secret: minio
  target: dev
