version: 2

sources:
  - name: ml_insights
    database: "{{ env_var('ICEBERG_CATALOG', 'minio') }}"
    schema: ml_insights
    tables:
      - name: raw_demand_forecast
        description: "Raw demand forecast events produced by ML workflows."
        external:
          location: "{{ env_var('ICEBERG_WAREHOUSE', 's3://warehouse') }}/ml_insights/raw_demand_forecast"
          format: iceberg
          options:
            allow_moved_paths: true
      - name: raw_stockout_risk
        description: "Raw stockout risk events produced by ML workflows."
        external:
          location: "{{ env_var('ICEBERG_WAREHOUSE', 's3://warehouse') }}/ml_insights/raw_stockout_risk"
          format: iceberg
          options:
            allow_moved_paths: true

models:
  - name: stg_forecast_demand
    description: "{{ doc('stg_forecast_demand') }}"
    columns:
      - name: event_id
        description: "Unique event identifier"
        tests:
          - not_null
          - unique
      - name: product_id
        description: "Product identifier"
      - name: region
        description: "Region of forecast"
      - name: forecast_ts
        description: "Timestamp for which the forecast applies"
      - name: forecast_qty
        description: "Predicted quantity"
      - name: event_date
        description: "Partition column derived from forecast_ts"
  - name: fact_forecast_demand
    description: "{{ doc('fact_forecast_demand') }}"
    columns:
      - name: event_id
        description: "Unique event identifier"
        tests:
          - not_null
          - unique
      - name: product_id
        description: "Product identifier"
      - name: region
        description: "Region of forecast"
      - name: forecast_ts
        description: "Timestamp for which the forecast applies"
      - name: forecast_qty
        description: "Predicted quantity"
      - name: event_date
        description: "Partition column derived from forecast_ts"
  - name: stg_stockout_risks
    description: "{{ doc('stg_stockout_risks') }}"
    columns:
      - name: event_id
        description: "Unique event identifier"
        tests:
          - not_null
          - unique
      - name: product_id
        description: "Product identifier"
      - name: risk_score
        description: "Predicted risk score"
      - name: predicted_date
        description: "Date of predicted stockout"
      - name: confidence
        description: "Prediction confidence"
      - name: event_date
        description: "Partition column derived from event_ts"
  - name: fact_stockout_risks
    description: "{{ doc('fact_stockout_risks') }}"
    columns:
      - name: event_id
        description: "Unique event identifier"
        tests:
          - not_null
          - unique
      - name: product_id
        description: "Product identifier"
      - name: risk_score
        description: "Predicted risk score"
      - name: predicted_date
        description: "Date of predicted stockout"
      - name: confidence
        description: "Prediction confidence"
      - name: event_date
        description: "Partition column derived from event_ts"
