version: 2

sources:
  - name: returns
    database: "{{ env_var('ICEBERG_CATALOG', 'minio') }}"
    schema: returns
    tables:
      - name: raw_returns
        description: "Raw returns ingested from RabbitMQ."
        external:
          location: "{{ env_var('ICEBERG_WAREHOUSE', 's3://warehouse') }}/returns/raw_returns"
          format: iceberg
          options:
            allow_moved_paths: true

models:
  - name: stg_returns
    description: "{{ doc('stg_returns') }}"
    columns:
      - name: return_id
        description: "Return identifier"
        tests:
          - not_null
      - name: order_id
        description: "Associated order identifier"
      - name: return_ts
        description: "Timestamp when the return occurred"
      - name: reason_code
        description: "Return reason code"
      - name: event_date
        description: "Partition column derived from return_ts"
  - name: fact_returns
    description: "{{ doc('fact_returns') }}"
    columns:
      - name: return_id
        description: "Unique return identifier"
        tests:
          - not_null
          - unique
      - name: order_id
        description: "Associated order identifier"
      - name: return_ts
        description: "Timestamp when the return occurred"
      - name: reason_code
        description: "Return reason code"
      - name: event_date
        description: "Partition column derived from return_ts"
