version: 2

sources:
  - name: orders
    schema: orders
    tables:
      - name: raw_orders
        description: "Raw orders ingested from RabbitMQ."
        external:
          location: "{{ env_var('ICEBERG_WAREHOUSE', 's3://warehouse') }}/orders/raw_orders"
          format: iceberg
          options:
            allow_moved_paths: true

models:
  - name: stg_orders
    description: "{{ doc('stg_orders') }}"
    columns:
      - name: order_id
        description: "Order identifier"
        tests:
          - not_null
      - name: product_id
        description: "Product identifier"
      - name: warehouse_id
        description: "Warehouse identifier"
      - name: order_ts
        description: "Timestamp when the order was placed"
      - name: qty
        description: "Ordered quantity"
      - name: event_date
        description: "Partition column derived from order_ts"
  - name: fact_orders
    description: "{{ doc('fact_orders') }}"
    columns:
      - name: order_id
        description: "Unique order identifier"
        tests:
          - not_null
          - unique
      - name: product_id
        description: "Product identifier"
      - name: warehouse_id
        description: "Warehouse identifier"
      - name: order_ts
        description: "Timestamp when the order was placed"
      - name: qty
        description: "Ordered quantity"
      - name: event_date
        description: "Partition column derived from order_ts"
